export const SEARCH_CHARACTER_REQUESTED = 'app/SEARCH_CHARACTER_REQUESTED';
export const SEARCH_CHARACTER_SUCCEEDED = 'app/SEARCH_CHARACTER_SUCCEEDED';
export const SEARCH_CHARACTER_FAILED = 'app/SEARCH_CHARACTER_FAILED';
export const SEARCH_CHARACTER_CLEAR_ERROR = 'app/SEARCH_CHARACTER_CLEAR_ERROR';
